### ISSUE TITLE
Drupal logout doesn't logout Moodle

### ISSUE THREAD

**Issue by ghost** [cannod/moodle-drupalservices#27]
I've followed the documentation and gotten the SSO to work (which is awesome). The only trouble I'm having is that when a user logs out of Drupal, they are not logged out of Moodle (the opposite direction works though). I did a couple searches and it seems like it should work but it's not for me.

**Comment by netw3rker** [comment]
Hi @dapperlibrarian , I've resolved this in the moodle_sso module on drupal.org. If you update it and configure it appropriately, it will log your users out of moodle too. Good luck and thanks for contributing!

**Comment by engr-noman** [comment]
hi i have configured moodle_sso module in appropriate way,login working fine but logout were not working i have added a redirect in moodle login.php which logout drupal,but now what should i do in drupal when you click on drupal site logout it also logout from moodle please help.
