### ISSUE TITLE
Fail : muser/Index: The muser resource is not available in the drupal service endpoint

### ISSUE THREAD

**Issue by Jhereck** [cannod/moodle-drupalservices#37]
Hello.

I tried to follow the installation instructions on the wiki, drupal side and moddle side (drupal and moodle modules up to date) on a local apache server, and got the "Fail : muser/Index: The muser resource is not available in the drupal service endpoint" error after hours of debugging.....

The messages are the followings : 

Success : cookies: SSO Cookie discovered properly
Success : system/connect: User session data reachable and you are logged in!
Success : user/login: Logged in to drupal!
Fail : muser/Index: The muser resource is not available in the drupal service endpoint.

And my "Services" export (checked all of the ressources to avoid errors/problems) : 

$endpoint = new stdClass();
$endpoint->disabled = FALSE; /* Edit this to true to make a default endpoint disabled initially */
$endpoint->api_version = 3;
$endpoint->name = 'moodlesso';
$endpoint->server = 'rest_server';
$endpoint->path = 'moodlesso';
$endpoint->authentication = array(
  'services' => 'services',
);
$endpoint->server_settings = array(
  'formatters' => array(
    'json' => TRUE,
    'xml' => TRUE,
    'bencode' => FALSE,
    'jsonp' => FALSE,
    'php' => FALSE,
  ),
  'parsers' => array(
    'application/json' => TRUE,
    'application/x-www-form-urlencoded' => TRUE,
    'text/xml' => TRUE,
    'application/vnd.php.serialized' => FALSE,
    'application/xml' => FALSE,
    'multipart/form-data' => FALSE,
  ),
);
$endpoint->resources = array(
  'comment' => array(
    'operations' => array(
      'create' => array(
        'enabled' => '1',
      ),
      'retrieve' => array(
        'enabled' => '1',
      ),
      'update' => array(
        'enabled' => '1',
      ),
      'delete' => array(
        'enabled' => '1',
      ),
      'index' => array(
        'enabled' => '1',
      ),
    ),
    'actions' => array(
      'countAll' => array(
        'enabled' => '1',
      ),
      'countNew' => array(
        'enabled' => '1',
      ),
    ),
  ),
  'file' => array(
    'operations' => array(
      'create' => array(
        'enabled' => '1',
      ),
      'retrieve' => array(
        'enabled' => '1',
      ),
      'delete' => array(
        'enabled' => '1',
      ),
      'index' => array(
        'enabled' => '1',
      ),
    ),
    'actions' => array(
      'create_raw' => array(
        'enabled' => '1',
      ),
    ),
  ),
  'moodlesso' => array(
    'operations' => array(
      'index' => array(
        'enabled' => '1',
      ),
    ),
  ),
  'node' => array(
    'operations' => array(
      'retrieve' => array(
        'enabled' => '1',
      ),
      'create' => array(
        'enabled' => '1',
      ),
      'update' => array(
        'enabled' => '1',
      ),
      'delete' => array(
        'enabled' => '1',
      ),
      'index' => array(
        'enabled' => '1',
      ),
    ),
    'relationships' => array(
      'files' => array(
        'enabled' => '1',
      ),
      'comments' => array(
        'enabled' => '1',
      ),
    ),
    'targeted_actions' => array(
      'attach_file' => array(
        'enabled' => '1',
      ),
    ),
  ),
  'system' => array(
    'actions' => array(
      'connect' => array(
        'enabled' => '1',
      ),
      'get_variable' => array(
        'enabled' => '1',
      ),
      'set_variable' => array(
        'enabled' => '1',
      ),
      'del_variable' => array(
        'enabled' => '1',
      ),
    ),
  ),
  'taxonomy_term' => array(
    'operations' => array(
      'retrieve' => array(
        'enabled' => '1',
      ),
      'create' => array(
        'enabled' => '1',
      ),
      'update' => array(
        'enabled' => '1',
      ),
      'delete' => array(
        'enabled' => '1',
      ),
      'index' => array(
        'enabled' => '1',
      ),
    ),
    'actions' => array(
      'selectNodes' => array(
        'enabled' => '1',
      ),
    ),
  ),
  'taxonomy_vocabulary' => array(
    'operations' => array(
      'retrieve' => array(
        'enabled' => '1',
      ),
      'create' => array(
        'enabled' => '1',
      ),
      'update' => array(
        'enabled' => '1',
      ),
      'delete' => array(
        'enabled' => '1',
      ),
      'index' => array(
        'enabled' => '1',
      ),
    ),
    'actions' => array(
      'getTree' => array(
        'enabled' => '1',
      ),
    ),
  ),
  'user' => array(
    'operations' => array(
      'retrieve' => array(
        'enabled' => '1',
      ),
      'create' => array(
        'enabled' => '1',
      ),
      'update' => array(
        'enabled' => '1',
      ),
      'delete' => array(
        'enabled' => '1',
      ),
      'index' => array(
        'enabled' => '1',
      ),
    ),
    'actions' => array(
      'login' => array(
        'enabled' => '1',
      ),
      'logout' => array(
        'enabled' => '1',
      ),
      'token' => array(
        'enabled' => '1',
      ),
      'request_new_password' => array(
        'enabled' => '1',
      ),
      'register' => array(
        'enabled' => '1',
      ),
    ),
    'targeted_actions' => array(
      'cancel' => array(
        'enabled' => '1',
      ),
      'password_reset' => array(
        'enabled' => '1',
      ),
      'resend_welcome_email' => array(
        'enabled' => '1',
      ),
    ),
  ),
);
$endpoint->debug = 0;

HELP please !!

**Comment by netw3rker** [comment]
@Jhereck I'm going to assume this issue is resolved with the latest updates. Please reopen this issue if it  happens again! thanks for reporting!
