### ISSUE TITLE
Not redirecting to Moodle after logging in when "destination" is used in the login URL

### ISSUE THREAD

**Issue by Cheesenbizkitz** [cannod/moodle-drupalservices#43]
When I go to a Moodle page that requires logging in, it does send me back to drupal with the destination at the end of the URL, e.g.:

Moodle is on study.example.org
Drupal is on dev.example.org

http://dev.example.org/user/login?destination=course/view.php?id=2

So that part is working.

And then I'm guessing that once you've logged in it's supposed to send you to the Moodle URL with the destination appended, but this doesn't happen for me. Once logged in, it will send me to the Drupal URL with the destination appended.

So when logging in with the above URL, I get sent to: 

http://dev.example.org/course/view.php?id=2

And that just gives me a page not found error.

I can find where the auth.php file appends the destination URL, but not where it's supposed to redirect it to after logging in, is this not fully implemented yet?

**Comment by Cheesenbizkitz** [comment]
Yep, this redirects perfectly!
Except I have one last issue that may or may not be related to this.

Every second time I click the log in button on Moodle it will work and send me to Drupal to log in with the moodle_url on the end like it's supposed to , but every other time it will send me just to "http://study.example.org/login/index.php" (study.example.org being my Moodle URL) and obviously I can't login with a drupalservices user there.

An example of the issue:
I'm on the Moodle site, not logged in to Drupal, then I click log in on Moodle, it'll then send me to Moodle's log in page, if I then go back a page and click log in again, it'll send me to Drupal like it's supposed to, then if I go back a page, back to Moodle and click log in again, it'll send me to Moodle's login page and continue like that if I keep going back to log in.

It happens every second time, and the first time always seems to go to Moodle.

Interestingly, when I do get sent to Moodle's login page, and refresh that page, it will send me to Drupal to log in.

**Comment by netw3rker** [comment]
I'm going to mark this as fixed and merge it into master & 2.x-2.x-dev. Thanks for the help in testing and fixing this!
