### ISSUE TITLE
Moodle stops importing users. No error given.

### ISSUE THREAD

**Issue by arua13l** [cannod/moodle-drupalservices#58]
So, the whole install works. I run cron repeatedly (because it only adds 20 users at a time) and I have over 300 to add to moodle form drupal. Then it just stops. It stops at 297 users and won't import any more. I can add them manually, but it just stops adding new users. I can recreate the error with a fresh moodle install, and the same thing happens. I could really use some help here and am willing to pay a small consultation fee if need be. Please let me know if you can help me out. I can be reached at arua13l@hotmail.com

**Comment by netw3rker** [comment]
I thought i fixed the issue of the import dying when a duplicate username was reached, but it might be worth a check to see if there's a username conflict. also unless you need the list of users to be always present and up-to-date, the need to copy users over isn't necessary with the 2.x version of the plugin. It creates or updates the user on login now.

**Comment by arua13l** [comment]
Hello!

Ok, I worked on this until 3:30am and here is where I am at.

I moved the site from a private host to godaddy last month because our grant was changing and we needed to get it moved. And I needed the Drupal and Moodle install to be on the same domain for the SSO to work and the private host wouldn't allow for a Moodle install.

Anyway, it appears that it ports over all the users that were created in the old site, but not a single one of the new users since the move.

It's like the SSO just doesn't even see the new users. 

I tried about 100 things:

Uninstalling and reinstalling Moodle SSO, updating the Features Module. A couple completely new Moodle installs with new Drupal services. I deleted and recreated the remote user. Creating a new user on Moodle that was the same as a new one on Drupal...

None of it had any effect.

I think I will create a new test user in Drupal and try logging into Moodle with them and see if it even recognizes them.

It just doesn't even think in needs to run drupalservices when cron runs. It's like the users are in some other db, but they aren't.

Any advice?

Thank you!
Laura

**Comment by arua13l** [comment]
Ok, so it was the admin user for the moodle account I entered during install and one of the admin users on the drupal install were duplicates. 

I ended up doing a completely new install with a different admin user name and email, and all is well.

Thank you so much for replying to me!

**Comment by netw3rker** [comment]
Nice work! glad it was something that easy, and thanks for letting me know!
