### ISSUE TITLE
I am locked out of moodle

### ISSUE THREAD

**Issue by goose2000** [cannod/moodle-drupalservices#60]
I mistakenly had 'force login' checked on before I had everything setup right. Now it tries to log me in when I visit the moodle part and fails. Is there a place in th DB I can undo this setting?

Thanks for ideas

**Comment by goose2000** [comment]
Nevermind, found it in mdl_config - there is the auth settings there

Sorry

**Comment by netw3rker** [comment]
You are my favorite issue opener/closer :)
