### ISSUE TITLE
Want to participate

### ISSUE THREAD

**Issue by kiklop74** [cannod/moodle-drupalservices#72]
Hello,

I would like to participate in this project and offer fixes for this module.

Darko

**Comment by netw3rker** [comment]
Great! I can use the help! Can you link me to a few pull requests you've submitted to this project? If you haven't done any yet, lets start off that way. There's no shortage of items to fix - our issue queue is at 21 open issues right now :)

**Comment by kiklop74** [comment]
I have nothing yet but when I do you will be the first to know.
