### ISSUE TITLE
My Moodle administrator is no longer an administrator

### ISSUE THREAD

**Issue by goose2000** [cannod/moodle-drupalservices#91]
Well, I'mtrying to figure it out (development site Drupal 8  M3.3), but today, somehow my moodle admin account (my only one), the userid got bumped up to 28, like I was a new user.

So, now I'm struggling to get my account back to admin role. I tried just setting it back to '2' but then moodle came back with an error as "Bad user id" when I crossed over from Drupal to Moodle, feel like this has happened before? Feels like the cron/update user function did this to me ?

**Comment by jacq0123** [comment]
Hello, did you resolve your issue? I'm unable to get Moodle 3.7 to work with Drupal 8. Are you using Moodle 3.7?
Thanks!

**Comment by goose2000** [comment]
I am closing this issue - think this works as designed.
